# Generated by Django 5.1.5 on 2025-02-21 23:50

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('heroic_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='instrumentcapability',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name_plural': 'Instrument Capabilities'},
        ),
        migrations.AlterModelOptions(
            name='observatory',
            options={'verbose_name_plural': 'Observatories'},
        ),
        migrations.AlterModelOptions(
            name='telescopestatus',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name_plural': 'Telescope Statuses'},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_name', models.CharField(blank=True, default='', help_text='Scimma Auth User Scram Credential name', max_length=256)),
                ('credential_password', models.CharField(blank=True, default='', help_text='Scimma Auth User Scram Credential password', max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='observatory',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroic_api.userproxy'),
        ),
    ]
