# Generated by Django 5.1.6 on 2025-03-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroic_api', '0002_userproxy_alter_instrumentcapability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(help_text='Instrument name', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentcapability',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('SCHEDULABLE', 'Schedulable')], default='AVAILABLE', help_text='Instrument availability status', max_length=32),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='id',
            field=models.CharField(max_length=63, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='name',
            field=models.CharField(help_text='Observatory Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.CharField(max_length=127, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(help_text='Site Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='name',
            field=models.CharField(help_text='Telescope Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='telescopestatus',
            name='target',
            field=models.CharField(blank=True, help_text='Target name for current pointing', max_length=255, null=True),
        ),
    ]
