# Generated by Django 5.1.7 on 2025-05-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroic_api', '0003_alter_instrument_id_alter_instrument_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_url',
            field=models.URLField(blank=True, help_text='Link to page with instrument information', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='weather_url',
            field=models.URLField(blank=True, help_text='Link to page with site weather information', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telescope',
            name='telescope_url',
            field=models.URLField(blank=True, help_text='Link to page with telescope information', max_length=255, null=True),
        ),
    ]
