# Generated by Django 5.2.1 on 2025-09-03 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroic_api', '0005_remove_telescopestatus_dec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this model was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When this model was last modified'),
        ),
        migrations.AddField(
            model_name='instrumentcapability',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this model was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observatory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this model was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observatory',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When this model was last modified'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this model was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When this model was last modified'),
        ),
        migrations.AddField(
            model_name='site',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this model was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When this model was last modified'),
        ),
        migrations.AddField(
            model_name='telescope',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this model was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telescope',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When this model was last modified'),
        ),
        migrations.AddField(
            model_name='telescopestatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this model was created'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlannedInstrumentCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True, help_text='Date when this planned instrument capability first applies')),
                ('end', models.DateTimeField(db_index=True, help_text='Date to stop considering this planned instrument capability')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('SCHEDULABLE', 'Schedulable')], default='AVAILABLE', help_text='Instrument availability status', max_length=32)),
                ('optical_element_groups', models.JSONField(blank=True, default=dict, help_text='Dictionary of Optical elements available for instrument')),
                ('operation_modes', models.JSONField(blank=True, default=dict, help_text='Dictionary of Operation modes available for instrument')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this model was created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When this model was last modified')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_capabilities', to='heroic_api.instrument')),
            ],
            options={
                'verbose_name_plural': 'Planned Instrument Capabilities',
                'ordering': ['start'],
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='PlannedTelescopeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True, help_text='Date when this planned telescope status first applies')),
                ('end', models.DateTimeField(db_index=True, help_text='Date to stop considering this planned telescope status')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('SCHEDULABLE', 'Schedulable')], default='AVAILABLE', help_text='Telescope Status', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for the planned telescope status', null=True)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Extra data related to the planned telescope status')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this model was created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When this model was last modified')),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_statuses', to='heroic_api.telescope')),
            ],
            options={
                'verbose_name_plural': 'Planned Telescope Statuses',
                'ordering': ['start'],
                'get_latest_by': 'date',
            },
        ),
    ]
