# Generated by Django 5.2.1 on 2025-09-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroic_api', '0006_instrument_created_instrument_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Instrument ID'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(help_text='Instrument name', max_length=255, verbose_name='Instrument Name'),
        ),
        migrations.AlterField(
            model_name='instrumentcapability',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('SCHEDULABLE', 'Queue Schedulable')], default='AVAILABLE', help_text='Instrument availability status', max_length=32),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='id',
            field=models.CharField(max_length=63, primary_key=True, serialize=False, verbose_name='Observatory ID'),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='name',
            field=models.CharField(help_text='Observatory Name', max_length=255, verbose_name='Observatory Name'),
        ),
        migrations.AlterField(
            model_name='plannedinstrumentcapability',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('SCHEDULABLE', 'Queue Schedulable')], default='AVAILABLE', help_text='Instrument availability status', max_length=32),
        ),
        migrations.AlterField(
            model_name='plannedtelescopestatus',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('SCHEDULABLE', 'Queue Schedulable')], default='AVAILABLE', help_text='Telescope Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.CharField(max_length=127, primary_key=True, serialize=False, verbose_name='Site ID'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(help_text='Site Name', max_length=255, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False, verbose_name='Telescope ID'),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='name',
            field=models.CharField(help_text='Telescope Name', max_length=255, verbose_name='Telescope Name'),
        ),
        migrations.AlterField(
            model_name='telescopestatus',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('SCHEDULABLE', 'Queue Schedulable')], default='AVAILABLE', help_text='Telescope Status', max_length=20),
        ),
    ]
