# Generated by Django 5.2.8 on 2026-01-30 00:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroic_api', '0007_alter_instrument_id_alter_instrument_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='footprint',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Footprint of the CCD of the instrument, in relative coordinates (centered on 0,0)', null=True, srid=4326),
        ),
    ]
