# Generated by Django 5.2.8 on 2026-01-30 01:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroic_api', '0008_instrument_footprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescopepointing',
            name='field',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='FOV for the current pointing in decimal degrees', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='telescopepointing',
            name='coordinate',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Central ra/dec for the current pointing in decimal degrees', srid=4326),
        ),
    ]
