# Generated by Django 5.2.8 on 2026-02-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroic_api', '0009_telescopepointing_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescopepointing',
            name='planned',
            field=models.BooleanField(default=False, help_text='This is a planned pointing for the future, it is subject to being deleted once its in the past.'),
        ),
        migrations.AddIndex(
            model_name='telescopepointing',
            index=models.Index(condition=models.Q(('planned', True)), fields=['planned'], name='tp_planned_idx'),
        ),
    ]
