name: Build

on:
  # Run this workflow for pushes on all branches
  push:
    branches:
      - '**'
  # Run this workflow when a tag or branch is created
  create:
  # Run this workflow for pull requests
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    services:
      postgres:
        image: postgis/postgis:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: heroic
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev 
        python -m pip install --upgrade pip
        python -m pip install 'poetry'
        poetry install
    - name: Run tests
      run: |
        poetry run coverage run manage.py test
        poetry run coverage xml
      env:
        DB_USER: postgres
        DB_PASS: postgres
        DB_HOST: localhost
        DB_PORT: 5432
    - name: Generate and send coveralls report
      uses: coverallsapp/github-action@v2.3.0
      with:
        parallel: true
        coverage-reporter-version: v0.6.9
  finish:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@v2.3.0
        with:
          parallel-finished: true
          coverage-reporter-version: v0.6.9
